# Generated by Django 4.0.5 on 2022-07-15 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='owner',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='listedItems', to=settings.AUTH_USER_MODEL),
        ),
    ]
