# Generated by Django 4.0.5 on 2022-07-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auctionitem_current_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionitem',
            old_name='starting_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='current_price',
        ),
    ]
