# Generated by Django 4.0.5 on 2022-07-19 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_starting_price_auctionitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
