# Generated by Django 4.0.5 on 2022-07-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='updated',
        ),
    ]
