# Generated by Django 4.0.5 on 2022-07-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='first',
            field=models.CharField(max_length=64),
        ),
    ]
